application: markridgwellcouk
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /static/(.*)
  static_files: static/\1
  upload: static/(.*)

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /google1ff5118afda594f4\.html
  static_files: google1ff5118afda594f4.html
  upload: google1ff5118afda594f4\.html

- url: /googleb9b28effe8247c2a\.html
  static_files: googleb9b28effe8247c2a.html
  upload: googleb9b28effe8247c2a\.html

- url: /mywot0240ebf0c66812002ba5\.html
  static_files: mywot0240ebf0c66812002ba5.html
  upload: mywot0240ebf0c66812002ba5\.html

- url: /y_key_6348032cd345c781\.html
  static_files: y_key_6348032cd345c781.html
  upload: y_key_6348032cd345c781\.html

- url: /robots\.txt
  static_files: robots.txt
  upload: robots\.txt

- url: /.*
  script: handlers.app

skip_files:
- ^(.*/)?\.pyproj
- ^(.*/)?\.sln
- ^\.gitignore
- ^\.git/(.*/)?

libraries:
- name: webapp2
  version: "2.5.2"

pagespeed:
  enabled_rewriters:
 - MinifyCss
 - ProxyCss
 - ProxyImages
 - ConvertMetaTags
 - InlineJs
 - InlinePreviewImages
 - CollapseWhitespace
 - CombineHeads
 - ElideAttributes
 - RemoveComments
 - RemoveQuotes
 - LeftTrimUrls
 - CombineCss
 - MoveCssToHead
 - CombineJs
 - JsOptimize
 - DeferJs
 - WebpOptimization
 - ImageConvertToJpeg
 - ImageRecompressJpeg
 - ImageProgressiveJpeg
 - ImageRecompressPng
 - ImageStripMetadata
 - ImageStripColorProfile
 - ImageResize
 - LazyloadImages
 - ImageAddDimensions

