application: markridgwellcouk
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /static/(.*)
  static_files: static/\1
  upload: static/(.*)

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /mywot0240ebf0c66812002ba5\.html
  static_files: mywot0240ebf0c66812002ba5.html
  upload: mywot0240ebf0c66812002ba5\.html

- url: /robots\.txt
  static_files: robots.txt
  upload: robots\.txt

- url: /tasks/sync
  script: tasksync.app
  secure: optional

- url: /tasks/photoofday
  script: taskphotoofday.app
  login: admin

- url: /rss\.xml
  script: rss.app
  secure: optional
- url: /rss/.*
  script: rss.app
  secure: optional


- url: /sitemap
  script: sitemap.app
  secure: optional

- url: /sitemap/.*
  script: sitemap.app
  secure: optional

- url: /about/
  script: about.app
  secure: optional

- url: /contact/
  script: contact.app
  secure: optional

- url: /albums/private/.*
  script: handlers.app
  login: required
  secure: always

- url: /.*
  script: handlers.app
  secure: optional

skip_files:
- ^(.*/)?\.pyproj
- ^(.*/)?\.sln
- ^\.gitignore
- ^\.git/(.*/)?

builtins:
- remote_api: off

pagespeed:
  domains_to_rewrite:
    - www.markridgwell.co.uk
    - www.markridgwell.com

libraries:
- name: webapp2
  version: "2.5.2"