application: markridgwellcouk
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /static/(.*)
  static_files: static/\1
  upload: static/(.*)
  expiration: "100d"

- url: /favicon\.ico
  mime_type: image/vnd.microsoft.icon
  static_files: favicon.ico
  upload: favicon\.ico
  expiration: "100d"

- url: /favicon\.png
  static_files: favicon.png
  upload: favicon\.png
  expiration: "100d"

- url: /mywot0240ebf0c66812002ba5\.html
  static_files: mywot0240ebf0c66812002ba5.html
  upload: mywot0240ebf0c66812002ba5\.html
  expiration: "100d"

- url: /robots\.txt
  static_files: robots.txt
  upload: robots\.txt
  expiration: "100d"

- url: /humans\.txt
  static_files: humans.txt
  upload: humans\.txt
  expiration: "100d"

- url: /crossdomain\.xml
  static_files: crossdomain.xml
  upload: crossdomain\.xml
  expiration: "100d"

- url: /large\.jpg
  static_files: large.jpg
  upload: large\.jpg
  expiration: "100d"

- url: /square\.jpg
  static_files: square.jpg
  upload: square\.jpg
  expiration: "100d"

- url: /tiny\.jpg
  static_files: tiny.jpg
  upload: tiny\.jpg
  expiration: "100d"

- url: /wide\.jpg
  static_files: wide.jpg
  upload: wide\.jpg
  expiration: "100d"

- url: /browserconfig\.xml
  static_files: browserconfig.xml
  upload: browserconfig\.xml
  expiration: "100d"

- url: /tasks/buffer
  script: taskbuffer.app
  secure: always
  login: admin

- url: /tasks/publish
  script: tasksync.app
  secure: optional

- url: /tasks/sync
  script: tasksync.app
  secure: optional

- url: /tasks/photoofday
  script: taskphotoofday.app
  login: admin

- url: /rss\.xml
  script: rss.app
  secure: optional

- url: /rss/.*
  script: rss.app
  secure: optional

- url: /RSS/.*
  script: rss.app
  secure: optional

- url: /sitemap
  script: sitemap.app
  secure: optional

- url: /sitemap/[a-zA-Z0-9]+
  script: sitemap.app
  secure: optional

- url: /about/
  script: about.app
  secure: optional

- url: /contact/
  script: contact.app
  secure: optional

- url: /albums/private/.*
  script: privatehandlers.app
  login: required
  secure: always

- url: /.*
  script: handlers.app
  secure: optional

- url: /.*
  script: notfound.app
  secure: optional

skip_files:
- ^(.*/)?\.pyproj
- ^(.*/)?\.sln
- ^\.gitignore
- ^\.git/(.*/)?
- ^\static/bootstrap/css/bootstrap\.css
- ^\static/bootstrap/css/bootstrap-theme\.css
- ^\static/bootstrap/js/bootstrap\bootstrap\.js

builtins:
- remote_api: off

pagespeed:
  domains_to_rewrite:
    - www.markridgwell.co.uk
    - www.markridgwell.com

libraries:
- name: webapp2
  version: "2.5.2"