#application: markridgwellcouk
#version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /_ah/xmpp/.*
  script: xmpphandler.app

- url: /_ah/bounce
  script: handle_bounced_email.app
  login: admin

- url: /static/(.*)
  static_files: static/\1
  upload: static/(.*)
  expiration: "100d"
  http_headers:
    Vary: DNT
    P3P: max-age=31536000
    Access-Control-Allow-Origin: 'self'
    Access-Control-Allow-Methods: GET, HEAD, OPTIONS
    Content-Security-Policy: frame-ancestors 'self'
    X-Frame-Options: DENY
    X-XSS-Protection: 1; mode=block
    X-Content-Type-Options: nosniff
    Referrer-Policy: no-referrer
    strict-transport-security: max-age=31536000; includeSubdomains; preload


- url: /favicon\.ico
  mime_type: image/vnd.microsoft.icon
  static_files: favicon.ico
  upload: favicon\.ico
  expiration: "100d"
  http_headers:
    Vary: DNT
    P3P: max-age=31536000
    Access-Control-Allow-Origin: 'self'
    Access-Control-Allow-Methods: GET, HEAD, OPTIONS
    Content-Security-Policy: frame-ancestors 'self'
    X-Frame-Options: DENY
    X-XSS-Protection: 1; mode=block
    X-Content-Type-Options: nosniff
    Referrer-Policy: no-referrer
    strict-transport-security: max-age=31536000; includeSubdomains; preload

- url: /favicon\.png
  static_files: favicon.png
  upload: favicon\.png
  expiration: "100d"
  http_headers:
    Vary: DNT
    P3P: max-age=31536000
    Access-Control-Allow-Origin: 'self'
    Access-Control-Allow-Methods: GET, HEAD, OPTIONS
    Content-Security-Policy: frame-ancestors 'self'
    X-Frame-Options: DENY
    X-XSS-Protection: 1; mode=block
    X-Content-Type-Options: nosniff
    Referrer-Policy: no-referrer
    strict-transport-security: max-age=31536000; includeSubdomains; preload

- url: /mywot0240ebf0c66812002ba5\.html
  static_files: mywot0240ebf0c66812002ba5.html
  upload: mywot0240ebf0c66812002ba5\.html
  expiration: "100d"
  http_headers:
    Vary: DNT
    P3P: max-age=31536000
    Access-Control-Allow-Origin: 'self'
    Access-Control-Allow-Methods: GET, HEAD, OPTIONS
    Content-Security-Policy: frame-ancestors 'self'
    X-Frame-Options: DENY
    X-XSS-Protection: 1; mode=block
    X-Content-Type-Options: nosniff
    Referrer-Policy: no-referrer
    strict-transport-security: max-age=31536000; includeSubdomains; preload

- url: /robots\.txt
  static_files: robots.txt
  upload: robots\.txt
  expiration: "100d"
  http_headers:
    Vary: DNT
    P3P: max-age=31536000
    Access-Control-Allow-Origin: 'self'
    Access-Control-Allow-Methods: GET, HEAD, OPTIONS
    Content-Security-Policy: frame-ancestors 'self'
    X-Frame-Options: DENY
    X-XSS-Protection: 1; mode=block
    X-Content-Type-Options: nosniff
    Referrer-Policy: no-referrer
    strict-transport-security: max-age=31536000; includeSubdomains; preload

- url: /humans\.txt
  static_files: humans.txt
  upload: humans\.txt
  expiration: "100d"
  http_headers:
    Vary: DNT
    P3P: max-age=31536000
    Access-Control-Allow-Origin: 'self'
    Access-Control-Allow-Methods: GET, HEAD, OPTIONS
    Content-Security-Policy: frame-ancestors 'self'
    X-Frame-Options: DENY
    X-XSS-Protection: 1; mode=block
    X-Content-Type-Options: nosniff
    Referrer-Policy: no-referrer
    strict-transport-security: max-age=31536000; includeSubdomains; preload

- url: /crossdomain\.xml
  static_files: crossdomain.xml
  upload: crossdomain\.xml
  expiration: "100d"
  http_headers:
    Vary: DNT
    P3P: max-age=31536000
    Access-Control-Allow-Origin: 'self'
    Access-Control-Allow-Methods: GET, HEAD, OPTIONS
    Content-Security-Policy: frame-ancestors 'self'
    X-Frame-Options: DENY
    X-XSS-Protection: 1; mode=block
    X-Content-Type-Options: nosniff
    Referrer-Policy: no-referrer
    strict-transport-security: max-age=31536000; includeSubdomains; preload

- url: /large\.jpg
  static_files: large.jpg
  upload: large\.jpg
  expiration: "100d"
  http_headers:
    Vary: DNT
    P3P: max-age=31536000
    Access-Control-Allow-Origin: 'self'
    Access-Control-Allow-Methods: GET, HEAD, OPTIONS
    Content-Security-Policy: frame-ancestors 'self'
    X-Frame-Options: DENY
    X-XSS-Protection: 1; mode=block
    X-Content-Type-Options: nosniff
    Referrer-Policy: no-referrer
    strict-transport-security: max-age=31536000; includeSubdomains; preload

- url: /square\.jpg
  static_files: square.jpg
  upload: square\.jpg
  expiration: "100d"
  http_headers:
    Vary: DNT
    P3P: max-age=31536000
    Access-Control-Allow-Origin: 'self'
    Access-Control-Allow-Methods: GET, HEAD, OPTIONS
    Content-Security-Policy: frame-ancestors 'self'
    X-Frame-Options: DENY
    X-XSS-Protection: 1; mode=block
    X-Content-Type-Options: nosniff
    Referrer-Policy: no-referrer
    strict-transport-security: max-age=31536000; includeSubdomains; preload

- url: /tiny\.jpg
  static_files: tiny.jpg
  upload: tiny\.jpg
  expiration: "100d"
  http_headers:
    Vary: DNT
    P3P: max-age=31536000
    Access-Control-Allow-Origin: 'self'
    Access-Control-Allow-Methods: GET, HEAD, OPTIONS
    Content-Security-Policy: frame-ancestors 'self'
    X-Frame-Options: DENY
    X-XSS-Protection: 1; mode=block
    X-Content-Type-Options: nosniff
    Referrer-Policy: no-referrer
    strict-transport-security: max-age=31536000; includeSubdomains; preload

- url: /wide\.jpg
  static_files: wide.jpg
  upload: wide\.jpg
  expiration: "100d"
  http_headers:
    Vary: DNT
    P3P: max-age=31536000
    Access-Control-Allow-Origin: 'self'
    Access-Control-Allow-Methods: GET, HEAD, OPTIONS
    Content-Security-Policy: frame-ancestors 'self'
    X-Frame-Options: DENY
    X-XSS-Protection: 1; mode=block
    X-Content-Type-Options: nosniff
    Referrer-Policy: no-referrer
    strict-transport-security: max-age=31536000; includeSubdomains; preload

- url: /browserconfig\.xml
  static_files: browserconfig.xml
  upload: browserconfig\.xml
  expiration: "100d"
  http_headers:
    Vary: DNT
    P3P: max-age=31536000
    Access-Control-Allow-Origin: 'self'
    Access-Control-Allow-Methods: GET, HEAD, OPTIONS
    Content-Security-Policy: frame-ancestors 'self'
    X-Frame-Options: DENY
    X-XSS-Protection: 1; mode=block
    X-Content-Type-Options: nosniff
    Referrer-Policy: no-referrer
    strict-transport-security: max-age=31536000; includeSubdomains; preload

- url: /tasks/buffer
  script: taskbuffer.app
  secure: always
  login: admin

- url: /tasks/kill
  script: taskkill.app
  secure: always
  login: admin

- url: /tasks/publish
  script: tasksync.app
  secure: optional

- url: /tasks/sync
  script: tasksync.app
  secure: optional

- url: /tasks/photoofday
  script: taskphotoofday.app
  login: admin

- url: /rss\.xml
  script: rss.app
  secure: optional

- url: /rss/.*
  script: rss.app
  secure: optional

- url: /RSS/.*
  script: rss.app
  secure: optional

- url: /sitemap
  script: sitemap.app
  secure: optional

- url: /sitemap/[a-zA-Z0-9]+
  script: sitemap.app
  secure: optional

- url: /about/
  script: about.app
  secure: optional

- url: /contact/
  script: contact.app
  secure: optional

- url: /albums/private/.*
  script: privatehandlers.app
  login: required
  secure: always

- url: /.*
  script: handlers.app
  secure: optional
  http_headers:

- url: /.*
  script: notfound.app
  secure: optional

skip_files:
- ^(.*/)?\.pyproj
- ^(.*/)?\.sln
- ^\.gitignore
- ^\.git/(.*/)?
- ^\static/bootstrap/css/bootstrap\.css
- ^\static/bootstrap/css/bootstrap-theme\.css
- ^\static/bootstrap/js/bootstrap\bootstrap\.js

builtins:
- remote_api: off

inbound_services:
 - mail_bounce
 - xmpp_message

libraries:
- name: webapp2
  version: "2.5.2"