runtime: python38

instance_class: F1

default_expiration: "30d"

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html
  secure: always
  redirect_http_response_code: 301
  http_headers:
    Content-Type: text/html; charset=UTF-8
    Content-Security-Policy: "default-src 'none'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; report-uri https://markridgwell.report-uri.com/r/d/csp/enforce"
    Expect-CT: max-age=0, report-uri="https://markridgwell.report-uri.com/r/d/ct/reportOnly"
    X-Frame-Options: DENY
    X-XSS-Protection: 1; mode=block; report=https://markridgwell.report-uri.com/r/d/xss/enforce
    X-Content-Type-Options: nosniff
    strict-transport-security: max-age=31536000; includeSubdomains; preload
    Referrer-Policy: no-referrer
    Feature-Policy: sync-xhr 'none'; document-domain 'none'; geolocation 'none'

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  secure: always
  redirect_http_response_code: 301
  http_headers:
    Content-Security-Policy: "default-src 'none'; report-uri: https://markridgwell.report-uri.com/r/d/csp/enforce"
    Expect-CT: max-age=0, report-uri="https://markridgwell.report-uri.com/r/d/ct/reportOnly"
    X-Frame-Options: DENY
    X-XSS-Protection: 1; mode=block; report=https://markridgwell.report-uri.com/r/d/xss/enforce
    X-Content-Type-Options: nosniff
    strict-transport-security: max-age=31536000; includeSubdomains; preload
    Referrer-Policy: no-referrer
    Feature-Policy: sync-xhr 'none'; document-domain 'none'; geolocation 'none'

- url: /humans.txt
  static_files: static/humans.txt
  upload: static/humans.txt
  secure: always
  redirect_http_response_code: 301
  http_headers:
    Content-Security-Policy: "default-src 'none'; report-uri https://markridgwell.report-uri.com/r/d/csp/enforce"
    Expect-CT: max-age=0, report-uri="https://markridgwell.report-uri.com/r/d/ct/reportOnly"
    X-Frame-Options: DENY
    X-XSS-Protection: 1; mode=block; report=https://markridgwell.report-uri.com/r/d/xss/enforce
    X-Content-Type-Options: nosniff
    strict-transport-security: max-age=31536000; includeSubdomains; preload
    Referrer-Policy: no-referrer
    Feature-Policy: sync-xhr 'none'; document-domain 'none'; geolocation 'none'

- url: /img
  static_dir: static/img
  secure: always
  redirect_http_response_code: 301
  expiration: "600d"
  http_headers:
    Content-Security-Policy: "default-src 'none';  report-uri https://markridgwell.report-uri.com/r/d/csp/enforce"
    Expect-CT: max-age=0, report-uri="https://markridgwell.report-uri.com/r/d/ct/reportOnly"
    X-Frame-Options: DENY
    X-XSS-Protection: 1; mode=block; report=https://markridgwell.report-uri.com/r/d/xss/enforce
    X-Content-Type-Options: nosniff
    strict-transport-security: max-age=31536000; includeSubdomains; preload
    Referrer-Policy: no-referrer
    Feature-Policy: sync-xhr 'none'; document-domain 'none'; geolocation 'none'

- url: /css
  static_dir: static/css
  secure: always
  redirect_http_response_code: 301
  expiration: "600d"
  http_headers:
    Content-Security-Policy: "default-src 'none'; img-src 'self' data:; report-uri https://markridgwell.report-uri.com/r/d/csp/enforce"
    Expect-CT: max-age=0, report-uri="https://markridgwell.report-uri.com/r/d/ct/reportOnly"
    X-Frame-Options: DENY
    X-XSS-Protection: 1; mode=block; report=https://markridgwell.report-uri.com/r/d/xss/enforce
    X-Content-Type-Options: nosniff
    strict-transport-security: max-age=31536000; includeSubdomains; preload
    Referrer-Policy: no-referrer
    Feature-Policy: sync-xhr 'none'; document-domain 'none'; geolocation 'none'
