name: Build and deploy

on:
  push:
    branches-ignore:
    - master

jobs:
  build_only:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: npm install --no-optional
      env:
        CI: false
    - run: |
            npm run build
            echo '***************************************************************************************************'
            echo '***************************************************************************************************'
            echo '***************************************************************************************************'
            ls -lR dst
      env:
        CI: false
