name: Build and deploy

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }} #service_account_email: ${{ secrets.GCP_SA_EMAIL }}
    - uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: npm install
      run: npm install
      env:
        CI: false
    - name: npm build
      run: |
            npm run build
            echo '***************************************************************************************************'
            echo '***************************************************************************************************'
            echo '***************************************************************************************************'
            ls -lR dst
      env:
        CI: false
    - name: Deploy
      run: |
             ls -lR dst
             gcloud app deploy dst/app.yaml --project ${{secrets.GCLOUD_PROJECT_ID}} --version v2020
